### ISSUE TITLE
[1.16.5] Crash while loading with Mac

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Keksuccino/FancyMenu-Support#157]
https://paste.ee/p/7lR09
From line 860 onwards is from what I'm told an Apple exclusive issue about stretching windows. This issue might be similar to the other mac related crash? https://github.com/Keksuccino/FancyMenu/issues/142#issue-807754884

Mac with Mojave 10.14.6
Current Java x64 build 281
minecraft 1.16.5
fancy menu 2.0.5
konkrete 1.1.5
Forge 36.1.0

from the Engineers Life 2 modpack.

**Comment by Keksuccino** [comment]
I. hate. macOS.
I don't even stretch/resize the window and everything happens in the frickin main thread. This error is so random, I don't get it. I literally just use the same method MC uses to set window icons and titles.

Thank you for telling me, but I'm not sure if I can fix this, because I have no clue why this even (still) happens.

**Comment by ZephyrWindSpirit** [comment]
It might be a Mojave issue because it removed 32-bit support? I don't know. 
Yes, the game starts normally when I remove fancymenu and konkrete, BUT
if I do a fresh instance of 1.16.5 with just fancymenu and konkrete, nothing else, it loads to the main screen.

**Comment by Keksuccino** [comment]
Hmm, interesting. And if you add the other mods to this new instance (+ fm and konkrete), does it start then? Or is it crashing again? Maybe a combination of FancyMenu and other mods is causing it.

But I think that’s really a random error and not really caused by FM, but MC + macOS in general.

**Comment by Keksuccino** [comment]
Closed because I wasn't able to reproduce this, I'm very sorry.
